In [1]:
import numpy as np
import os

# 定义 .npz 文件所在的目录
npz_directory = '/home/hh/Documents/DeepLSD/my_experiment'

# 列出目录中的所有 .npz 文件
npz_files = [f for f in os.listdir(npz_directory) if f.endswith('.npz')]

# 查看每个 .npz 文件的内容
for npz_file in npz_files:
    npz_path = os.path.join(npz_directory, npz_file)
    data = np.load(npz_path)
    
    print(f"Contents of {npz_file}:")
    for key in data.files:
        print(f" - {key}: shape {data[key].shape}")


Contents of 00061141_deeplsd.npz:
 - lines: shape (204, 2, 2)
 - warped_lines: shape (200, 2, 2)
Contents of 00085319_deeplsd.npz:
 - lines: shape (168, 2, 2)
 - warped_lines: shape (95, 2, 2)
Contents of 00401754_deeplsd.npz:
 - lines: shape (173, 2, 2)
 - warped_lines: shape (144, 2, 2)
Contents of 00079712_deeplsd.npz:
 - lines: shape (66, 2, 2)
 - warped_lines: shape (41, 2, 2)
Contents of 00222614_deeplsd.npz:
 - lines: shape (83, 2, 2)
 - warped_lines: shape (40, 2, 2)
Contents of 00066069_deeplsd.npz:
 - lines: shape (152, 2, 2)
 - warped_lines: shape (91, 2, 2)
Contents of 00037045_deeplsd.npz:
 - lines: shape (132, 2, 2)
 - warped_lines: shape (82, 2, 2)
Contents of 00384487_deeplsd.npz:
 - lines: shape (253, 2, 2)
 - warped_lines: shape (90, 2, 2)
Contents of 00064861_deeplsd.npz:
 - lines: shape (221, 2, 2)
 - warped_lines: shape (176, 2, 2)
Contents of 00491341_deeplsd.npz:
 - lines: shape (68, 2, 2)
 - warped_lines: shape (47, 2, 2)
Contents of 00225046_deeplsd.npz:
 - lin

Contents of 00072579_deeplsd.npz:
 - lines: shape (207, 2, 2)
 - warped_lines: shape (148, 2, 2)
Contents of 00518667_deeplsd.npz:
 - lines: shape (172, 2, 2)
 - warped_lines: shape (144, 2, 2)
Contents of 00075702_deeplsd.npz:
 - lines: shape (185, 2, 2)
 - warped_lines: shape (185, 2, 2)
Contents of 00076000_deeplsd.npz:
 - lines: shape (192, 2, 2)
 - warped_lines: shape (171, 2, 2)
Contents of 00059391_deeplsd.npz:
 - lines: shape (141, 2, 2)
 - warped_lines: shape (59, 2, 2)
Contents of 00494116_deeplsd.npz:
 - lines: shape (112, 2, 2)
 - warped_lines: shape (98, 2, 2)
Contents of 00104125_deeplsd.npz:
 - lines: shape (149, 2, 2)
 - warped_lines: shape (119, 2, 2)
Contents of 00051420_deeplsd.npz:
 - lines: shape (154, 2, 2)
 - warped_lines: shape (111, 2, 2)
Contents of 00052167_deeplsd.npz:
 - lines: shape (181, 2, 2)
 - warped_lines: shape (75, 2, 2)
Contents of 00423627_deeplsd.npz:
 - lines: shape (222, 2, 2)
 - warped_lines: shape (180, 2, 2)
Contents of 00037184_deeplsd.npz:

In [2]:
import numpy as np

# 加载 .npz 文件
file_path = '/home/hh/Documents/DeepLSD/my_experiment/detection_wireframe/deeplsd.npz'
data = np.load(file_path)

# 查看文件中的数组键名
print("文件中的数组键名：", data.files)

# 逐个查看每个数组的内容和形状
for key in data.files:
    print(f"键名: {key}, 数组形状: {data[key].shape}")
    print(data[key])  # 打印数组内容

文件中的数组键名： ['struct_rep', 'struct_loc_error', 'orth_rep', 'orth_loc_error', 'H_estim', 'num_lines']
键名: struct_rep, 数组形状: (5,)
[0.32582543 0.55626218 0.63080645 0.66649845 0.69005404]
键名: struct_loc_error, 数组形状: (5,)
[0.48784167 0.72013972 1.02974684 1.32421532 1.38838806]
键名: orth_rep, 数组形状: (5,)
[0.49177768 0.67661258 0.7237103  0.74196771 0.75247826]
键名: orth_loc_error, 数组形状: (5,)
[0.24356617 0.41679843 0.66013345 0.91573328 0.9766902 ]
键名: H_estim, 数组形状: ()
0.9458874458874459
键名: num_lines, 数组形状: ()
132.06709956709958


In [3]:
# 如果你只想查看某个特定键的内容，可以这样做：
specific_key = 'struct_loc_error'  # 替换为实际的键名
if specific_key in data.files:
    print(f"{specific_key} 的内容：")
    print(data[specific_key])
else:
    print(f"键名 '{specific_key}' 不存在于文件中。")

struct_loc_error 的内容：
[0.48784167 0.72013972 1.02974684 1.32421532 1.38838806]
